<template>
    <div id="about" style="margin-top:100px;" class="container">
       <h4 style="color:#192F60;text-align:center;font-family: 'Bebas Neue', cursive;font-size:30px;">About</h4>
        <p style="font-family: 'Noto Sans', sans-serif;color:#192F60;text-align:center;font-size:16px;">No. 1 towing app to download</p>
        <div class="row mt-5">
            <div class="col-3">
                <img src="/images/main_page/logo.png" class="img-fluid" />
            </div>
            <div class="col-9">
                <p class="iban" style="box-sizing: border-box; margin: 0px 0px 15px; padding: 0px; font-size: 13px; line-height: 24px; text-align: left; color: rgb(25, 47, 96); font-family: &quot;Noto Sans Japanese&quot;, &quot;ヒラギノ角ゴ Pro W3&quot;, &quot;Hiragino Kaku Gothic Pro&quot;, メイリオ, Meiryo, Osaka, &quot;ＭＳ Ｐゴシック&quot;, &quot;MS PGothic&quot;, verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">UBR-TOWING is the No.1 towing app in store&nbsp;<span class="kome" style="box-sizing: border-box; font-size: 8px; color: rgb(102, 102, 102);">(*)</span> .&nbsp;This app covers everything from towing arrangements and reservations to towing payments.</p>
                <p class="iban" style="box-sizing: border-box; margin: 0px 0px 15px; padding: 0px; font-size: 13px; line-height: 24px; text-align: left; color: rgb(25, 47, 96); font-family: &quot;Noto Sans Japanese&quot;, &quot;ヒラギノ角ゴ Pro W3&quot;, &quot;Hiragino Kaku Gothic Pro&quot;, メイリオ, Meiryo, Osaka, &quot;ＭＳ Ｐゴシック&quot;, &quot;MS PGothic&quot;, verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">With UBR-TOWING, you don't have to go out on the main street to pick up a towing or queue up in front of the station. A tow will pick you up at your fingertips.</p>
                <p class="iban" style="box-sizing: border-box; margin: 0px 0px 15px; padding: 0px; font-size: 13px; line-height: 24px; text-align: left; color: rgb(25, 47, 96); font-family: &quot;Noto Sans Japanese&quot;, &quot;ヒラギノ角ゴ Pro W3&quot;, &quot;Hiragino Kaku Gothic Pro&quot;, メイリオ, Meiryo, Osaka, &quot;ＭＳ Ｐゴシック&quot;, &quot;MS PGothic&quot;, verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="color: rgb(25, 47, 96); font-family: &quot;Noto Sans Japanese&quot;, &quot;ヒラギノ角ゴ Pro W3&quot;, &quot;Hiragino Kaku Gothic Pro&quot;, メイリオ, Meiryo, Osaka, &quot;ＭＳ Ｐゴシック&quot;, &quot;MS PGothic&quot;, verdana, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 600; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Take a service at UBR-TOWING.</span></p>
            </div>
        </div>
    </div>
</template>